cam_model: Pinhole
cam_width: 640
cam_height: 540
scale: 1.0
cam_fx: 208.08279418945312
cam_fy: 208.1546630859375
cam_cx: 317.1446533203125
cam_cy: 281.7761535644531
cam_d0: 0.6388027667999268
cam_d1: 0.24633248150348663
cam_d2: 0.00013934666640125215
cam_d3: -8.393820462515578e-05
cam_d4: 0.004469867795705795
cam_d5: 0.5882253050804138
cam_d6: 0.30361810326576233
cam_d7: 0.02370571158826351
cam_d8: 0.0
cam_d9: 0.0
cam_d10: 0.0
cam_d11: 0.0
cam_d12: 0.0
cam_d13: 0.0
