common:
  img_topic: "/lx_camera_node/LxCamera_Rgb"
  lid_topic: "/lx_camera_node/LxCamera_LidarCloud"
  imu_topic: "/lx_camera_node/LxCamera_Imu"
  img_en: 1
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  extrinsic_T: [0.014, -0.008, 0.022]
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  Rcl: [0.999970058255676,-0.007575300979631972,0.0015803187045515376,0.00758337184806947,0.9999579056243075,-0.0051652154710413135,-0.0015411241202044675,0.0051770449598553805,0.9999854114645522]
  Pcl: [0.00012788176646623279,0.01630264791514122,0.00017512556539685652]

time_offset: 
  imu_time_offset: 0.0
  img_time_offset: -0.150
  exposure_time_init: 0
  lid_time_interval: 0.1

preprocess:
  point_filter_num: 3
  filter_size_surf: 0.1
  lidar_type: 8 # Livox Avia LiDAR
  scan_line: 160
  blind: 1.0

imu:
  imu_en: true
  imu_int_frame: 30
  acc_cov: 1.0
  gyr_cov: 1.0
  b_acc_cov: 0.0001
  b_gyr_cov: 0.0001

vio:
  max_iterations: 10
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000 
  patch_size: 8
  patch_pyrimid_level: 3
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

lio:
  max_iterations: 10
  dept_err: 0.02
  beam_err: 0.05
  min_eigen_value: 0.0025 # 0.005
  voxel_size: 0.5
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

local_map:
  map_sliding_en: false
  half_map_size: 100
  sliding_thresh: 8

uav:
  imu_rate_odom: false
  gravity_align_en: true

publish:
  dense_map_en: true
  pub_effect_point_en: false
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "xz9"
  pose_output_en: false

pcd_save:
  pcd_save_en: true
  colmap_output_en: true # need to set interval = -1
  filter_size_pcd: 0.1
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
